### ISSUE TITLE
LDSDKRegisterService协议中的handleResultUrl:方法 和 LDSDKHandleURLProtocol协议中的handleURL:方法有什么区别

### ISSUE THREAD

**Issue by unkosun** [poholo/LDSDKManager_IOS#2]
LDSDKRegisterService协议中的handleResultUrl:方法 和 LDSDKHandleURLProtocol协议中的handleURL:有什么区别。我看到支付宝实例中处理回调结果都是用的handleURL:方法，但是这个方法内没有处理支付完成后的回调结果处理，而是放在handleResultUrl:方法中实现，是不是有问题？

**Comment by poholo** [comment]
抱歉支付这块由于目前缺乏相关的测试号做的比较粗糙~
现在虽然有pay这块代码，但基本都没有验证

**Comment by unkosun** [comment]
> 抱歉支付这块由于目前缺乏相关的测试号做的比较粗糙~
> 现在虽然有pay这块代码，但基本都没有验证

好的

**Comment by poholo** [comment]
刚修正了支付的问题，可以用新版本试试 1.0.9

**Comment by poholo** [comment]
刚修正了支付的问题，可以用新版本试试 1.0.9
